
targets:
  $default:
    builders:
      mediator|mediator_init_builder:
        enabled: true
        options:
          generate_for:
            - lib/**/*.dart

builders:
  mediator|mediator_init_builder:
    target: ":mediator"
    import: "package:dart_mediatr/src/mediator_generator.dart"
    builder_factories: ["mediatorInitBuilder"]
    build_extensions: { ".dart": [".mediator.dart"] }
    auto_apply: dependents
    build_to: source